### ISSUE TITLE
aspell_dict_info_list_size always returns zero

### ISSUE THREAD

**Issue by aspell-helper** [GNUAspell/aspell#155]
**Nathan Fredrickson *<noif\@sf>* created a bug report on 2004-09-09 01:56:57 UTC**
*(Orig. from https://sourceforge.net/p/aspell/bugs/98)*

aspell\_dict\_info\_list\_size always returns zero
reguardless of how many dictionaries are actually
described in the list.

Test progam attached.
gcc -o test -laspell test.c

**Comment by rrthomas** [comment]
Enchant maintainer here: I just looked at this issue because it tripped me up some years ago when I was working on the Enchant aspell back-end. As far as I can see, this API is still not marked as unimplemented. Could it be removed from the header file and/or marked as unimplemented, please? (Or even better, just implement it?)

Thanks for working on aspell all these years, @kevina !

**Comment by kevina** [comment]
I can mark it as unimplemented.  I don't want to remove the function as that will break ABI comparability, and removing them from the header file will be difficult as the header file is automatically generated.

**Comment by rrthomas** [comment]
Removing a function that always returns zero seems to be a fairly small break, but I understand! Marking as unimplemented would have saved me the trouble I've had, so that would be great.

**Comment by rrthomas** [comment]
Thanks!
